// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gduaqbfwvtlyefyawkwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkdWFxYmZ3dnRseWVmeWF3a3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDgyMzksImV4cCI6MjA2NzMyNDIzOX0.vBUHMwZmwq6ff6dASORx4iEUWAVUWwygNBtPzRLA3l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});